---
server:
    address: "0.0.0.0"
    port: 80

redirects:
  - from: site1.domain.com
    to: https://www.yahoo.com/
    with: 302

  - from: site2.domain.com
    to: https://www.google.com/
    with: 302
